// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtgjycgjdzmgnzshhzak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0Z2p5Y2dqZHptZ256c2hoemFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Mzg0MjcsImV4cCI6MjA2MDExNDQyN30.cxPESrJvEQZfXL8mpVuR66JkM_3_n0hC8MTES5EIaDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);